/*
 * ExceptionDialogView.java
 *
 * Created on May 28, 2007, 8:29 PM
 */

package net.sf.xpontus.gui.defaults;

/**
 * A default error dialog to display usefull messages 
 * @author  Yves Zoundi
 */
public class ExceptionDialogView extends javax.swing.JDialog {
    
    public static ExceptionDialogView INSTANCE;
    
    /**
     * 
     * @return THE SINGLE instance of this class
     */
    public static ExceptionDialogView getInstance(){
        if(INSTANCE == null){
            INSTANCE = new ExceptionDialogView();
        }
        return INSTANCE;
    }
    
    /** Creates new form ExceptionDialogView */
    private ExceptionDialogView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    } 
    
    private ExceptionDialogView(){
        this(null, true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        closeButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        messagesTA = new javax.swing.JTextArea();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Error");
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        messagesTA.setColumns(20);
        messagesTA.setLineWrap(true);
        messagesTA.setRows(5);
        messagesTA.setWrapStyleWord(true);
        scrollPane.setViewportView(messagesTA);

        errorLabel.setText("An error occured! Please look at the messages in the textbox");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(errorLabel))
                    .add(layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(scrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(342, Short.MAX_VALUE)
                        .add(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(errorLabel)
                .add(34, 34, 34)
                .add(scrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(closeButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed
     
    
    public void setMessage(String errorMessage){
        this.messagesTA.setText(errorMessage);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextArea messagesTA;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    
}
