/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package net.sf.xpontus.view.editor.syntax.sql;

public interface SQLParserConstants {

  int EOF = 0;
  int K_ALL = 5;
  int K_CREATE = 6;
  int K_PRIMARY = 7;
  int K_REFERENCES = 8;
  int K_FOREIGN = 9;
  int K_CONSTRAINT = 10;
  int K_KEY = 11;
  int K_AND = 12;
  int K_ANY = 13;
  int K_AS = 14;
  int K_ASC = 15;
  int K_BEGIN = 16;
  int K_BETWEEN = 17;
  int K_BINARY_INTEGER = 18;
  int K_BOOLEAN = 19;
  int K_BY = 20;
  int K_CHAR = 21;
  int K_CLOSE = 22;
  int K_COMMENT = 23;
  int K_COMMIT = 24;
  int K_CONNECT = 25;
  int K_CONSTANT = 26;
  int K_CURRENT = 27;
  int K_CURSOR = 28;
  int K_DATE = 29;
  int K_DECIMAL = 30;
  int K_DECLARE = 31;
  int K_DEFAULT = 32;
  int K_DELETE = 33;
  int K_DESC = 34;
  int K_DISTINCT = 35;
  int K_DO = 36;
  int K_ELSE = 37;
  int K_ELSIF = 38;
  int K_END = 39;
  int K_EXCEPTION = 40;
  int K_EXCEPTION_INIT = 41;
  int K_EXCLUSIVE = 42;
  int K_EXISTS = 43;
  int K_EXIT = 44;
  int K_FETCH = 45;
  int K_FLOAT = 46;
  int K_FOR = 47;
  int K_FROM = 48;
  int K_FUNCTION = 49;
  int K_GOTO = 50;
  int K_GROUP = 51;
  int K_HAVING = 52;
  int K_IF = 53;
  int K_IN = 54;
  int K_INDEX = 55;
  int K_INSERT = 56;
  int K_INTEGER = 57;
  int K_INTERSECT = 58;
  int K_INTO = 59;
  int K_IS = 60;
  int K_LEVEL = 61;
  int K_LIKE = 62;
  int K_LOCK = 63;
  int K_LOOP = 64;
  int K_MINUS = 65;
  int K_MODE = 66;
  int K_NATURAL = 67;
  int K_NOT = 68;
  int K_NOWAIT = 69;
  int K_NULL = 70;
  int K_NUMBER = 71;
  int K_OF = 72;
  int K_ONLY = 73;
  int K_OPEN = 74;
  int K_OR = 75;
  int K_ORDER = 76;
  int K_OTHERS = 77;
  int K_OUT = 78;
  int K_PACKAGE = 79;
  int K_POSITIVE = 80;
  int K_PRAGMA = 81;
  int K_PRIOR = 82;
  int K_PROCEDURE = 83;
  int K_RAISE = 84;
  int K_READ = 85;
  int K_REAL = 86;
  int K_RECORD = 87;
  int K_REF = 88;
  int K_RETURN = 89;
  int K_REVERSE = 90;
  int K_ROLLBACK = 91;
  int K_ROW = 92;
  int K_SAVEPOINT = 93;
  int K_SEGMENT = 94;
  int K_SELECT = 95;
  int K_SET = 96;
  int K_SHARE = 97;
  int K_SMALLINT = 98;
  int K_SQL = 99;
  int K_START = 100;
  int K_TABLE = 101;
  int K_THEN = 102;
  int K_TO = 103;
  int K_TRANSACTION = 104;
  int K_UNION = 105;
  int K_UPDATE = 106;
  int K_USE = 107;
  int K_VALUES = 108;
  int K_VARCHAR2 = 109;
  int K_VARCHAR = 110;
  int K_WHEN = 111;
  int K_WHERE = 112;
  int K_WHILE = 113;
  int K_WITH = 114;
  int K_WORK = 115;
  int K_WRITE = 116;
  int S_NUMBER = 117;
  int FLOAT = 118;
  int INTEGER = 119;
  int DIGIT = 120;
  int SINGLE_LINE_COMMENT = 121;
  int START_MULTILINE_COMMENT = 122;
  int END_MULTILINE_COMMENT = 123;
  int MULTILINE_COMMENT_CHAR = 124;
  int S_IDENTIFIER = 125;
  int LETTER = 126;
  int SPECIAL_CHARS = 127;
  int S_BIND = 128;
  int S_CHAR_LITERAL = 129;
  int S_QUOTED_IDENTIFIER = 130;

  int DEFAULT = 0;
  int IN_MULTILINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"ALL\"",
    "\"CREATE\"",
    "\"PRIMARY\"",
    "\"REFERENCES\"",
    "\"FOREIGN\"",
    "\"CONSTRAINT\"",
    "\"KEY\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"BEGIN\"",
    "\"BETWEEN\"",
    "\"BINARY_INTEGER\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"CHAR\"",
    "\"CLOSE\"",
    "\"COMMENT\"",
    "\"COMMIT\"",
    "\"CONNECT\"",
    "\"CONSTANT\"",
    "\"CURRENT\"",
    "\"CURSOR\"",
    "\"DATE\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DISTINCT\"",
    "\"DO\"",
    "\"ELSE\"",
    "\"ELSIF\"",
    "\"END\"",
    "\"EXCEPTION\"",
    "\"EXCEPTION_INIT\"",
    "\"EXCLUSIVE\"",
    "\"EXISTS\"",
    "\"EXIT\"",
    "\"FETCH\"",
    "\"FLOAT\"",
    "\"FOR\"",
    "\"FROM\"",
    "\"FUNCTION\"",
    "\"GOTO\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"IF\"",
    "\"IN\"",
    "\"INDEX\"",
    "\"INSERT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"LEVEL\"",
    "\"LIKE\"",
    "\"LOCK\"",
    "\"LOOP\"",
    "\"MINUS\"",
    "\"MODE\"",
    "\"NATURAL\"",
    "\"NOT\"",
    "\"NOWAIT\"",
    "\"NULL\"",
    "\"NUMBER\"",
    "\"OF\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"OTHERS\"",
    "\"OUT\"",
    "\"PACKAGE\"",
    "\"POSITIVE\"",
    "\"PRAGMA\"",
    "\"PRIOR\"",
    "\"PROCEDURE\"",
    "\"RAISE\"",
    "\"READ\"",
    "\"REAL\"",
    "\"RECORD\"",
    "\"REF\"",
    "\"RETURN\"",
    "\"REVERSE\"",
    "\"ROLLBACK\"",
    "\"ROW\"",
    "\"SAVEPOINT\"",
    "\"SEGMENT\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"SHARE\"",
    "\"SMALLINT\"",
    "\"SQL\"",
    "\"START\"",
    "\"TABLE\"",
    "\"THEN\"",
    "\"TO\"",
    "\"TRANSACTION\"",
    "\"UNION\"",
    "\"UPDATE\"",
    "\"USE\"",
    "\"VALUES\"",
    "\"VARCHAR2\"",
    "\"VARCHAR\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WHILE\"",
    "\"WITH\"",
    "\"WORK\"",
    "\"WRITE\"",
    "<S_NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<MULTILINE_COMMENT_CHAR>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_BIND>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":=\"",
    "\"%TYPE\"",
    "\"%ROWTYPE\"",
    "\"<<\"",
    "\">>\"",
    "\".\"",
    "\"..\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"||\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"%FOUND\"",
    "\"%NOTFOUND\"",
    "\"%ISOPEN\"",
    "\"%ROWCOUNT\"",
    "\"!=\"",
    "\"#\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\".*\"",
  };

}
