/*
 * EditorPanel.java
 *
 * Created on 28 janvier 2008, 04:55
 */
package net.sf.xpontus.modules.gui.components.preferences;

import java.awt.Component;
import java.awt.Font;
import java.io.File;
import java.nio.charset.Charset;
import java.util.Iterator;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;
import net.sf.xpontus.constants.XPontusConfigurationConstantsIF;
import net.sf.xpontus.plugins.preferences.PreferencesPluginIF;
import net.sf.xpontus.utils.PropertiesConfigurationLoader;
import net.sf.xpontus.utils.XPontusComponentsUtils;

/**
 *
 * @author  Yves Zoundi <yveszoundi at users dot sf dot net>
 */
public class EditorPanel extends javax.swing.JPanel implements IPreferencesPanel, PreferencesPluginIF {

    private Integer value = new Integer(700);
    private Integer min = new Integer(500);
    private Integer max = new Integer(1000);
    private Integer step = new Integer(100);
    private SpinnerNumberModel model = new SpinnerNumberModel(value, min, max, step);
    private DefaultComboBoxModel encodingModel;
 
    /**
     * 
     * @return
     */
    @Override
    public String toString() {
        return getTitle();
    }

    /** Creates new form EditorPanel */
    public EditorPanel() {
        encodingModel = new DefaultComboBoxModel();
        Iterator<String> it = Charset.availableCharsets().keySet().iterator();
        while (it.hasNext()) {
            encodingModel.addElement(it.next());
        }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayLineNumbersOption = new javax.swing.JCheckBox();
        chooseFontButton = new javax.swing.JButton();
        fontValueLabel = new javax.swing.JLabel();
        tabSizeLabel = new javax.swing.JLabel();
        tabSizeTF = new javax.swing.JFormattedTextField();
        cursorBlinkRateLabel = new javax.swing.JLabel();
        cursorBlinkRateValues = new javax.swing.JSpinner();
        encodingLabel = new javax.swing.JLabel();
        encodingList = new javax.swing.JComboBox();

        displayLineNumbersOption.setSelected(true);
        displayLineNumbersOption.setText("Display line numbers");

        chooseFontButton.setText("Font...");
        chooseFontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFontButtonActionPerformed(evt);
            }
        });

        fontValueLabel.setFont(UIManager.getFont("EditorPane.font"));
        fontValueLabel.setText(getStringFont(UIManager.getFont("EditorPane.font")));

        tabSizeLabel.setText("Tab size");

        tabSizeTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        tabSizeTF.setValue(new Integer(4));

        cursorBlinkRateLabel.setText("Cursor blink rate");

        cursorBlinkRateValues.setModel(model);

        encodingLabel.setText("Default XML encoding");

        encodingList.setModel(encodingModel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseFontButton)
                            .addComponent(tabSizeLabel)
                            .addComponent(cursorBlinkRateLabel)
                            .addComponent(encodingLabel))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(encodingList, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fontValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tabSizeTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cursorBlinkRateValues, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(displayLineNumbersOption, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayLineNumbersOption)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cursorBlinkRateLabel)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cursorBlinkRateValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabSizeLabel)
                    .addComponent(tabSizeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseFontButton)
                    .addComponent(fontValueLabel))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encodingLabel)
                    .addComponent(encodingList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void chooseFontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFontButtonActionPerformed
        Component frame = XPontusComponentsUtils.getTopComponent().getDisplayComponent();
        Font selectedFont = UIManager.getFont("EditorPane.font");

//        Font f = JFontChooser.showDialog(frame, "Select font", selectedFont);
//        if (f != null) {
//            fontValueLabel.setText(getStringFont(f));
//            fontValueLabel.setFont(f);
//            fontValueLabel.repaint();
//        }
}//GEN-LAST:event_chooseFontButtonActionPerformed

    public String getStringFont(Font f) {
        String style = "Bold Italic";

        switch (f.getStyle()) {
            case Font.ITALIC:
                style = "Italic";
                break;
            case Font.BOLD:
                style = "Bold";
                break;
            case 3:
                style = "Bold Italic";
                break;
            case Font.PLAIN:
                style = "Plain";
                break;
            default:
                style = "Plain";
                break;
        }

        return f.getFamily() + "," + style + "," + f.getSize();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseFontButton;
    private javax.swing.JLabel cursorBlinkRateLabel;
    private javax.swing.JSpinner cursorBlinkRateValues;
    private javax.swing.JCheckBox displayLineNumbersOption;
    private javax.swing.JLabel encodingLabel;
    private javax.swing.JComboBox encodingList;
    private javax.swing.JLabel fontValueLabel;
    private javax.swing.JLabel tabSizeLabel;
    private javax.swing.JFormattedTextField tabSizeTF;
    // End of variables declaration//GEN-END:variables
    public String getTitle() {
        return "Editor";
    }

    public Component getJComponent() {
        return this;
    }

    public String getId() {
        return getClass().getName();
    }

    public String getPluginCategory() {
       return "";
    }

    public IPreferencesPanel getPreferencesPanelComponent() {
        return this;
    }

    public void saveSettings() {
        PropertiesConfigurationLoader.save(propertiesFile, properties);
    }

    public void loadSettings() {
        if(true){
            return;
        }
        //load the properties
        properties = PropertiesConfigurationLoader.load(propertiesFile); 
        
        String[] f = properties.getProperty("Font").split(",");
        String family = f[0].trim();
        String style1 = f[1].trim();
        int style = Font.PLAIN;
        
        if(style1.trim().equals("Bold")){
            style = Font.BOLD;
        }
        else if(style1.trim().equals("Bold Italic")){
            style  = 3;
        }
        int size = Integer.parseInt(f[2].trim());
        
        this.displayLineNumbers = Boolean.valueOf(properties.getProperty("displayLineNumbers"));
        this.editorFont = new Font(family, style, size);
        this.cursorBlinkRate = Integer.parseInt(properties.getProperty("cursorBlinkRate"));
        this.defaultXMLEncoding = properties.getProperty("DefaultXMLEncoding").toString();
        
        this.displayLineNumbersOption.setSelected(displayLineNumbers);
        this.fontValueLabel.setText(getStringFont(editorFont) );
        this.fontValueLabel.setFont(editorFont);
        this.encodingList.setSelectedItem(defaultXMLEncoding);
        this.cursorBlinkRateValues.setValue(Integer.valueOf(cursorBlinkRate));
        this.tabSizeTF.setValue(Integer.valueOf(size));
    }
    
    private File propertiesFile = XPontusConfigurationConstantsIF.EDITOR_PREFERENCES_FILE;
    private Properties properties;
    private int cursorBlinkRate;
    private boolean displayLineNumbers;
    private Font editorFont;
    private String defaultXMLEncoding;
}
