/* Generated By:JavaCC: Do not edit this line. PropertyParserConstants.java */
package net.sf.xpontus.view.editor.syntax.properties;

public interface PropertyParserConstants
  {
    int EOF = 0;
    int NEWLINE = 1;
    int BLANK_LINE = 2;
    int CONTINUATION = 3;
    int COMMENT = 4;
    int BARE_KEY = 5;
    int KEY = 6;
    int OTHER = 7;
    int EQUALS = 8;
    int VALUE = 9;
    int DEFAULT = 0;
    int ParseEquals = 1;
    int ParseValue = 2;
    String[] tokenImage = 
        {
            "<EOF>", "<NEWLINE>", "<BLANK_LINE>", "<CONTINUATION>", "<COMMENT>",
            "<BARE_KEY>", "<KEY>", "<OTHER>", "<EQUALS>", "<VALUE>",
        };
  }
