/*
 * TemplateFormView.java
 *
 * Created on 1 août 2005, 17:57
 *
 *  Copyright (C) 2005 Yves Zoundi
 *
 *  This library is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation; either version 2.1 of the License, or
 *  (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

package net.sf.xpontus.view;


import java.net.URL;
import org.apache.commons.io.FilenameUtils;
//import org.syntax.jedit.tokenmarker.TokenMarker;

/**
 * The template dialog to create new files
 * @author  Yves Zoundi
 */
public class TemplateFormView extends javax.swing.JDialog {
    
    
    /** Creates new form TemplateFormView */
    public TemplateFormView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        templateList.setSelectedIndex(0);
    }
    
    public TemplateFormView(){
        this(XPontusWindow.getInstance().getFrame(), true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        templateList = new javax.swing.JList();
        jRadioButton1 = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(XPontusWindow.getInstance().getI18nMessage("form.template.title"));
        titleLabel.setText(XPontusWindow.getInstance().getI18nMessage("form.template.title"));
        
        scrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        scrollPane.setMinimumSize(new java.awt.Dimension(460, 160));
        scrollPane.setPreferredSize(new java.awt.Dimension(460, 160));
        templateList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "XML", "XSL", "HTML", "Docbook XML", "XSL FO", "XML Schema", "Relax NG", "Apache Ant", "Other" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollPane.setViewportView(templateList);
        
        
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(XPontusWindow.getInstance().getI18nMessage("builtin.template.key"));
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        
        okButton.setText(XPontusWindow.getInstance().getI18nMessage("ok.key"));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        
        
        cancelButton.setText(XPontusWindow.getInstance().getI18nMessage("cancel.key"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        
        
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(titleLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 400, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jRadioButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 347, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(scrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 400, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createSequentialGroup()
                .add(79, 79, 79)
                .add(okButton)
                .add(74, 74, 74)
                .add(cancelButton)))
                .addContainerGap(24, Short.MAX_VALUE))
                );
        
        
        layout.linkSize(new java.awt.Component[] {cancelButton, okButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);
        
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .add(titleLabel)
                .add(15, 15, 15)
                .add(jRadioButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(38, 38, 38)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(okButton)
                .add(cancelButton))
                .addContainerGap(26, Short.MAX_VALUE))
                );
        pack();
    }//GEN-END:initComponents
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try{
            setVisible(false);
            java.io.InputStream is;
            int index = templateList.getSelectedIndex();
            String tmpl = templates[index];
            URL url = getClass().getResource("/net/sf/xpontus/templates/" + tmpl);
            String ext = FilenameUtils.getExtension(templates[templateList.getSelectedIndex()]);
            XPontusWindow.getInstance().getTabContainer().createEditorFromURL(url);
        } catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(
                    XPontusWindow.getInstance().getFrame(),
                    e.getLocalizedMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    private final String templates[] = {
        "template.xml", "template.xsl", "template.html", "docbook.xml", "template.fo", "template.xsd", "template.rng", "ant-template.xml", "template.txt"
    };
    
    
// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton okButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JList templateList;
    private javax.swing.JLabel titleLabel;
// End of variables declaration//GEN-END:variables
    
}
