/* Generated By:JavaCC: Do not edit this line. PHPParserConstants.java */
package net.sf.xpontus.view.editor.syntax.php;

public interface PHPParserConstants {

  int EOF = 0;
  int PHP_BEGIN = 1;
  int PHP_EXPR = 2;
  int HTML_OTHER = 3;
  int HTML = 4;
  int INTEGER_LITERAL = 9;
  int DECIMAL_LITERAL = 10;
  int HEX_LITERAL = 11;
  int OCTAL_LITERAL = 12;
  int FLOATING_POINT_LITERAL = 13;
  int EXPONENT = 14;
  int DOUBLE_STRING_LITERAL_START = 15;
  int SINGLE_STRING_LITERAL_START = 16;
  int HEREDOC_START = 17;
  int SLASH_SLASH_COMMENT = 18;
  int NUMERAL_COMMENT = 19;
  int SLASH_STAR_COMMENT = 20;
  int SINGLE_STRING_LITERAL_END = 22;
  int DOUBLE_STRING_LITERAL_END = 26;
  int DSL_SIMPLE_VAR_START = 27;
  int DSL_COMPLEX_VAR_START = 28;
  int TEXT = 30;
  int DSL_COMPLEX_VAR_END = 31;
  int DSL_CV_TEXT = 32;
  int DSL_SIMPLE_VAR_END = 33;
  int DSL_SIMPLE_STRING_VAR_END = 34;
  int DSL_SIMPLE_VAR_WASNT = 35;
  int HD1 = 40;
  int HD2 = 45;
  int REQUIRE_ONCE = 47;
  int REQUIRE = 48;
  int INCLUDE_ONCE = 49;
  int INCLUDE = 50;
  int DEFINE = 51;
  int ECHO = 52;
  int PRINT = 53;
  int SWITCH = 54;
  int CASE = 55;
  int DFLT = 56;
  int BREAK = 57;
  int RETURN = 58;
  int DO = 59;
  int WHILE = 60;
  int FOREACH = 61;
  int AS = 62;
  int FOR = 63;
  int CONTINUE = 64;
  int IF = 65;
  int ELSE = 66;
  int ELSEIF = 67;
  int AND = 68;
  int OR = 69;
  int XOR = 70;
  int NOT = 71;
  int FUNCTION = 72;
  int CLASS = 73;
  int EXTENDS = 74;
  int VAR = 75;
  int PUBLIC = 76;
  int PRIVATE = 77;
  int PROTECTED = 78;
  int ABSTRACT = 79;
  int FINAL = 80;
  int STATIC = 81;
  int INTERFACE = 82;
  int IMPLEMENTS = 83;
  int CONST = 84;
  int CLONE = 85;
  int INSTANCEOF = 86;
  int GLOBAL = 87;
  int ARRAY = 88;
  int NEW = 89;
  int PREDEFINED_CONSTANT = 90;
  int PHP_END = 91;
  int DOLLAR = 92;
  int SEMICOLON = 93;
  int TRY = 94;
  int CATCH = 95;
  int THROW = 96;
  int VAR_NAME = 97;
  int LETTER1 = 98;
  int DIGIT1 = 99;
  int DOLLAR1 = 100;
  int VARTYPE = 101;
  int IDENTIFIER = 102;
  int LETTER = 103;
  int DIGIT = 104;

  int HTML_STATE = 0;
  int DEFAULT = 1;
  int SINGLE_STRING_LITERAL = 2;
  int SSL_SPECIAL = 3;
  int DOUBLE_STRING_LITERAL = 4;
  int DSL_COMPLEX_VAR = 5;
  int DSL_SIMPLE_VAR = 6;
  int DSL_SPECIAL = 7;
  int HEREDOC1 = 8;
  int HEREDOC = 9;
  int HEREDOC2 = 10;
  int VAR_NAME_STATE = 11;

  String[] tokenImage = {
    "<EOF>",
    "<PHP_BEGIN>",
    "\"<?=\"",
    "<HTML_OTHER>",
    "<HTML>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"<<<\"",
    "<SLASH_SLASH_COMMENT>",
    "<NUMERAL_COMMENT>",
    "<SLASH_STAR_COMMENT>",
    "\"\\\\\"",
    "\"\\\'\"",
    "<token of kind 23>",
    "<token of kind 24>",
    "<token of kind 25>",
    "\"\\\"\"",
    "\"$\"",
    "<DSL_COMPLEX_VAR_START>",
    "\"\\\\\"",
    "<TEXT>",
    "\"}\"",
    "<DSL_CV_TEXT>",
    "<DSL_SIMPLE_VAR_END>",
    "\"\\\"\"",
    "<DSL_SIMPLE_VAR_WASNT>",
    "<token of kind 36>",
    "<token of kind 37>",
    "<token of kind 38>",
    "<token of kind 39>",
    "<HD1>",
    "<token of kind 41>",
    "\"\\n\"",
    "<token of kind 43>",
    "\"\\n\"",
    "<HD2>",
    "<token of kind 46>",
    "\"require_once\"",
    "\"require\"",
    "\"include_once\"",
    "\"include\"",
    "\"define\"",
    "\"echo\"",
    "\"print\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"break\"",
    "\"return\"",
    "\"do\"",
    "\"while\"",
    "\"foreach\"",
    "\"as\"",
    "\"for\"",
    "\"continue\"",
    "\"if\"",
    "\"else\"",
    "\"elseif\"",
    "\"and\"",
    "\"or\"",
    "\"xor\"",
    "\"not\"",
    "\"function\"",
    "\"class\"",
    "\"extends\"",
    "\"var\"",
    "\"public\"",
    "\"private\"",
    "\"protected\"",
    "\"abstract\"",
    "\"final\"",
    "\"static\"",
    "\"interface\"",
    "\"implements\"",
    "\"const\"",
    "\"clone\"",
    "\"instanceof\"",
    "\"global\"",
    "\"array\"",
    "\"new\"",
    "<PREDEFINED_CONSTANT>",
    "\"?>\"",
    "\"$\"",
    "\";\"",
    "\"try\"",
    "\"catch\"",
    "\"throw\"",
    "<VAR_NAME>",
    "<LETTER1>",
    "<DIGIT1>",
    "\"$\"",
    "<VARTYPE>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"=>\"",
    "\"&\"",
    "\"=\"",
    "\"@\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\".=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"?\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"==\"",
    "\"!=\"",
    "\"===\"",
    "\"!==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\".\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\"++\"",
    "\"--\"",
    "\"->\"",
    "\"::\"",
    "\"[\"",
    "\"]\"",
  };

}
