/* Generated By:JavaCC: Do not edit this line. DTDParserConstants.java */
package net.sf.xpontus.view.editor.syntax.dtd;

public interface DTDParserConstants {

  int EOF = 0;
  int LETTER = 1;
  int DIGIT = 2;
  int NAMECHAR = 3;
  int FIXED = 4;
  int IMPLIED = 5;
  int PCDATA = 6;
  int REQUIRED = 7;
  int ELEMENT = 8;
  int ATTLIST = 9;
  int CDATA = 10;
  int ANY = 11;
  int EMPTY = 12;
  int ID = 13;
  int IDREF = 14;
  int IDREFS = 15;
  int ENTITY = 16;
  int ENTITIES = 17;
  int NMTOKEN = 18;
  int NMTOKENS = 19;
  int NOTATION = 20;
  int NAME = 21;
  int QUOTEDSTR = 22;
  int COMMENT_START = 24;
  int TEXT_IN_COMMENT = 25;
  int ERR_IN_COMMENT = 26;
  int COMMENT_END = 27;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<LETTER>",
    "<DIGIT>",
    "<NAMECHAR>",
    "\"#FIXED\"",
    "\"#IMPLIED\"",
    "\"#PCDATA\"",
    "\"#REQUIRED\"",
    "\"<!ELEMENT\"",
    "\"<!ATTLIST\"",
    "\"CDATA\"",
    "\"ANY\"",
    "\"EMPTY\"",
    "\"ID\"",
    "\"IDREF\"",
    "\"IDREFS\"",
    "\"ENTITY\"",
    "\"ENTITIES\"",
    "\"NMTOKEN\"",
    "\"NMTOKENS\"",
    "\"NOTATION\"",
    "<NAME>",
    "<QUOTEDSTR>",
    "<token of kind 23>",
    "\"<!--\"",
    "<TEXT_IN_COMMENT>",
    "<ERR_IN_COMMENT>",
    "\"-->\"",
    "\">\"",
    "\"(\"",
    "\"|\"",
    "\")*\"",
    "\")\"",
    "\",\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
  };

}
