/*
 * ApplyScenarioView.java
 *
 *
 * Created on 1 août 2005, 17:46
 *
 *  Copyright (C) 2005-2007 Yves Zoundi
 *
 *  This library is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation; either version 2.1 of the License, or
 *  (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

package net.sf.xpontus.view;


import com.sun.java.help.impl.SwingWorker;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListModel;
import net.sf.xpontus.core.utils.L10nHelper;
import net.sf.xpontus.model.ScenarioListModel;
import net.sf.xpontus.model.ScenarioModel;
import net.sf.xpontus.utils.MsgUtils;
import net.sf.xpontus.utils.XMLUtils2;

/**
 * Dialog to execute an XSLT scenario
 * @author  Yves Zoundi
 */
public class ApplyScenarioView extends javax.swing.JDialog {
    
    private L10nHelper locale;
    private MsgUtils _msg;
    
    /**
     * Creates new form ApplyScenarioView
     * @param parent The parent window
     * @param modal specify if the window is modal or not
     */
    public ApplyScenarioView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        _msg = MsgUtils.getInstance();
        locale = L10nHelper.getInstance();
        ScenarioListModel obj = (ScenarioListModel)new ScenarioListModel().load();
        _list = obj.getScenarioList();
        _model = new DefaultComboBoxModel(_list);
        initComponents();
        if(_list.size()>0){
            scenarioList.setSelectedIndex(0);
        }
    }
    
    /**
     * 
     */
    public ApplyScenarioView(){
        this(XPontusWindow.getInstance().getFrame(),true);
    }
    
    /**
     * 
     * @param b 
     */
    public void setVisible(boolean b){
        ScenarioListModel obj = (ScenarioListModel)new ScenarioListModel().load();
        _list = obj.getScenarioList();
        _model = new javax.swing.DefaultComboBoxModel(_list);
        scenarioList.setModel(_model);
        scenarioList.revalidate();
        if(_list.size()>0){
            scenarioList.setSelectedIndex(0);
        }
        super.setVisible(b);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        scenarioList = new javax.swing.JList();
        buttonsPanel = new javax.swing.JPanel();
        applyButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(locale.getValue("form.applyscenario.title"));
        panel.setLayout(new java.awt.BorderLayout());

        panel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
        panel.setMinimumSize(new java.awt.Dimension(280, 150));
        panel.setPreferredSize(new java.awt.Dimension(280, 150));
        scenarioList.setModel(_model);
        scrollPane.setViewportView(scenarioList);

        panel.add(scrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        applyButton.setText(locale.getValue("form.applyscenario.transform"));
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButton_Onclick(evt);
            }
        });

        buttonsPanel.add(applyButton);

        closeButton.setText(locale.getValue("form.applyscenario.close"));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton_Onclick(evt);
            }
        });

        buttonsPanel.add(closeButton);

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    private void applyButton_Onclick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButton_Onclick
        ListModel model = scenarioList.getModel();
        int index = scenarioList.getSelectedIndex();
        if(index == -1){
            javax.swing.JOptionPane.showMessageDialog(XPontusWindow.getInstance()
            .getFrame(),
                    _msg.getString("msg.selectScenario"), _msg.getString("msg.error"),
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            
            return;
        }
        final ScenarioModel scenario = (ScenarioModel) _model.getElementAt(index);
        if(!scenario.isExternal()){
            if(XPontusWindow.getInstance().getCurrentEditor()==null){
                javax.swing.JOptionPane.showMessageDialog(XPontusWindow.getInstance()
                .getFrame(),
                        _msg.getString("msg.openDocument"), _msg.getString("msg.error"),
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                
                return;
            }}
        String log = "Beginning transformation ...";
        XPontusWindow.getInstance().getStatusBar().setOperationMessage(log);
        SwingWorker worker = new SwingWorker() {
            public Object construct() {
                XMLUtils2.getInstance().transform(scenario);
                return null;
            }
        };
        worker.start();
        setVisible(false);
    }//GEN-LAST:event_applyButton_Onclick
    
    private void closeButton_Onclick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton_Onclick
        setVisible(false);
    }//GEN-LAST:event_closeButton_Onclick
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel panel;
    private javax.swing.JList scenarioList;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    private java.util.Vector _list;
    private javax.swing.DefaultComboBoxModel _model;
}
