/*
 * SplashScreen.java
 *
 * Created on October 30, 2005, 2:45 PM
 *
 *
 *  Copyright (C) 2005-2007 Yves Zoundi
 *
 *  This library is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation; either version 2.1 of the License, or
 *  (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

package net.sf.xpontus.view;

import net.sf.xpontus.core.utils.L10nHelper;

/**
 * The application splash screen
 * @author  Yves Zoundi
 */
public class SplashScreen extends javax.swing.JWindow {
    
    private L10nHelper locale;
    
    /** Creates new form BeanForm */
    public SplashScreen() {
        locale = L10nHelper.getInstance();
        initComponents();
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        aboutLabel = new javax.swing.JLabel();

        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panel.setMaximumSize(new java.awt.Dimension(220, 86));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/xpontus/icons/Eclipse/logo.png")));
        panel.add(logoLabel);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        descriptionLabel.setFont(new java.awt.Font("Dialog", 1, 11));
        descriptionLabel.setForeground(new java.awt.Color(0, 102, 204));
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText(locale.getValue("form.about.description"));
        descriptionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(descriptionLabel, java.awt.BorderLayout.NORTH);

        aboutLabel.setFont(new java.awt.Font("Dialog", 1, 11));
        aboutLabel.setForeground(new java.awt.Color(204, 0, 0));
        aboutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutLabel.setText(locale.getValue("form.about.programmer"));
        getContentPane().add(aboutLabel, java.awt.BorderLayout.SOUTH);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
    
}
