/*
 * XMLDiffFormView.java
 *
 * Created on May 30, 2006, 6:52 PM
 *
 *
 *  Copyright (C) 2005-2007 Yves Zoundi
 *
 *  This library is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation; either version 2.1 of the License, or
 *  (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

package net.sf.xpontus.view;

import javax.swing.JFileChooser;
import net.sf.xpontus.controller.actions.XMLDiffAction;

/**
 * A dialog to inspect xml document differences
 * @author  Yves Zoundi
 */
public class XMLDiffFormView extends javax.swing.JDialog {
    
    /** Creates new form XMLDiffFormView */
    public XMLDiffFormView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        action = new XMLDiffAction();
        initComponents();
    }
    
    /** Creates new form XMLDiffFormView */
    public XMLDiffFormView() {
        this(XPontusWindow.getInstance().getFrame(), true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        chooser = new javax.swing.JFileChooser();
        file1Button = new javax.swing.JButton();
        file1TF = new javax.swing.JTextField();
        file2Button = new javax.swing.JButton();
        file2TF = new javax.swing.JTextField();
        diffButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("XMLDiff");
        file1Button.setText("First file ...");
        file1Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        file1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file1ButtonActionPerformed(evt);
            }
        });

        file1TF.setEditable(false);

        file2Button.setText("Second file ...");
        file2Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        file2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file2ButtonActionPerformed(evt);
            }
        });

        file2TF.setEditable(false);

        diffButton.setAction(action);
        diffButton.setText("Perform diff...");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(33, 33, 33)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(file1Button)
                            .add(file2Button))
                        .add(35, 35, 35)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(file1TF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .add(file2TF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(81, 81, 81)
                        .add(diffButton)
                        .add(57, 57, 57)
                        .add(closeButton)))
                .add(25, 25, 25))
        );

        layout.linkSize(new java.awt.Component[] {closeButton, diffButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {file1Button, file2Button}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(41, 41, 41)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(file1Button)
                    .add(file1TF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(file2Button)
                    .add(file2TF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(54, 54, 54)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(diffButton)
                    .add(closeButton))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void file2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file2ButtonActionPerformed
        int answer = chooser.showOpenDialog(this);
        if(answer == JFileChooser.APPROVE_OPTION){
            action.setFile2(chooser.getSelectedFile());
            file2TF.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_file2ButtonActionPerformed

    private void file1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file1ButtonActionPerformed
        int answer = chooser.showOpenDialog(this);
        if(answer == JFileChooser.APPROVE_OPTION){
            action.setFile1(chooser.getSelectedFile());
            file1TF.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_file1ButtonActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser chooser;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton diffButton;
    private javax.swing.JButton file1Button;
    private javax.swing.JTextField file1TF;
    private javax.swing.JButton file2Button;
    private javax.swing.JTextField file2TF;
    // End of variables declaration//GEN-END:variables
    private XMLDiffAction action;
}
