Document: xpontus
Title: Debian xpontus Manual
Author: <insert document author here>
Abstract: This manual describes what xpontus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xpontus/xpontus.sgml.gz

Format: postscript
Files: /usr/share/doc/xpontus/xpontus.ps.gz

Format: text
Files: /usr/share/doc/xpontus/xpontus.text.gz

Format: HTML
Index: /usr/share/doc/xpontus/html/index.html
Files: /usr/share/doc/xpontus/html/*.html

  
