/*
 * InstalledPluginsPanel.java
 *
 * Created on December 26, 2007, 10:41 PM
 */
package net.sf.xpontus.plugins.pluginsbrowser.browser;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.DefaultTableModel;
import org.java.plugin.registry.PluginDescriptor; 
/**
 *
 * @author  mrcheeks
 */
public class InstalledPluginsPanel extends javax.swing.JPanel {
    private DefaultTableModel tableModel;

    /** Creates new form InstalledPluginsPanel */
    public InstalledPluginsPanel() {
        //	setLayout(new java.awt.BorderLayout());


//        Dimension dim = new Dimension(400,450);
//        
//        this.setPreferredSize(dim);
//        this.setMinimumSize(dim);


        //        DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();

        Object[] descriptors = PBPlugin.r.getPluginDescriptors().toArray();

        java.util.Vector columns = new java.util.Vector(3);
        columns.add("Identifier");
        columns.add("Category");
        columns.add("Built-in");

        //        String[] columns = {"Identifier", "Category", "Built-in"};

        //String[][] rows = new String[columns.length][descriptors.length];

        java.util.Vector rows = new java.util.Vector();


        for (int i = 0; i < descriptors.length; i++) {
            PluginDescriptor pds = (PluginDescriptor) descriptors[i];
            String id = pds.getId().toString();
//            System.out.println("Id:" + id);
            String category = pds.getAttribute("Category").getValue().toString();
            String builtin = pds.getAttribute("Built-in").getValue().toString();

            java.util.Vector m_row = new java.util.Vector(3);
            m_row.add(id);
            m_row.add(category);
            m_row.add(builtin);

            rows.add(m_row);
        /*	    rows[0, i] = id;
        rows[1, i] = category;
        rows[2, i] = builtin;*/
        }

        tableModel = new DefaultTableModel(rows, columns) {

            public boolean isCellEditable(int row,
                    int column) {
                return false;
            }
        };

        initComponents();

        this.jTable1.setPreferredScrollableViewportSize(new Dimension(400, 400));

        javax.swing.JPanel sPanel = new javax.swing.JPanel();
        javax.swing.BoxLayout sLayout = new javax.swing.BoxLayout(sPanel, javax.swing.BoxLayout.Y_AXIS);
        sPanel.setLayout(sLayout);

        Border b1 = BorderFactory.createEmptyBorder(3, 3, 3, 3);
        Border b2 = BorderFactory.createEmptyBorder(2, 2, 2, 2);

        sPanel.setBorder(new CompoundBorder(b1, b2));

        sPanel.add(new javax.swing.JButton("Install"));

        sPanel.add(new javax.swing.JLabel(" "));

        sPanel.add(new javax.swing.JButton("Upgrade"));

        sPanel.add(new javax.swing.JLabel(" "));

        javax.swing.JButton removePluginButton = new javax.swing.JButton("Remove");

        removePluginButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        sPanel.add(new javax.swing.JButton("Remove"));

        add(sPanel, java.awt.BorderLayout.EAST);

//        ((VLJTable)jTable1).installFilter(0, new RegExpFilter(true)); 
    //	 System.out.println("nb plugins:" + tableModel.getRowCount());


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
