/*
 * JTidyPanel.java
 *
 * Created on February 16, 2006, 8:00 PM
 */

package net.sf.xpontus.view.components.options;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.beans.BeanAdapter;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JComponent;
import net.sf.xpontus.model.options.JTidyOptionModel;

/**
 *
 * @author  Owner
 */
public class JTidyPanel extends javax.swing.JPanel implements IOptionPanel{
    BeanAdapter adapter;
    /** Creates new form JTidyPanel */
    public JTidyPanel() {
        model = new JTidyOptionModel();
        adapter = new BeanAdapter(model, true);
        initComponents();
        read();
    }
    
    public JComponent getControl() {
        return this;
    }
    
    public String getDisplayName() {
        return "JTidy";
    }
    
    public void read(){
        JTidyOptionModel m = new JTidyOptionModel();
        JTidyOptionModel obj = (JTidyOptionModel)m.load();
        
        model.setDropEmptyParasOption(obj.isDropEmptyParasOption());
        model.setIndentOption(obj.isIndentOption());
        model.setLogicalEmphasisOption(obj.isLogicalEmphasisOption());
        model.setUppercaseAttrOption(obj.isUppercaseAttrOption());
        model.setUppercaseTagsOption(obj.isUppercaseTagsOption());
        model.setWrapAttrOption(obj.isWrapAttrOption());
    }
    
    public void save(){
        model.save();
    }
    
    
    /**
     *
     * @return
     */
    public javax.swing.JCheckBox getDropEmptyParasOption() {
        return dropEmptyParasOption;
    }
    
    /**
     *
     * @param dropEmptyParasOption
     */
    public void setDropEmptyParasOption(javax.swing.JCheckBox dropEmptyParasOption) {
        this.dropEmptyParasOption = dropEmptyParasOption;
    }
    
    /**
     *
     * @return
     */
    public javax.swing.JCheckBox getIndentOption() {
        return indentOption;
    }
    
    /**
     *
     * @param indentOption
     */
    public void setIndentOption(javax.swing.JCheckBox indentOption) {
        this.indentOption = indentOption;
    }
    
    /**
     *
     * @return
     */
    public javax.swing.JCheckBox getLogicalEmphasisOption() {
        return logicalEmphasisOption;
    }
    
    /**
     *
     * @param logicalEmphasisOption
     */
    public void setLogicalEmphasisOption(javax.swing.JCheckBox logicalEmphasisOption) {
        this.logicalEmphasisOption = logicalEmphasisOption;
    }
    
    
    /**
     *
     * @return
     */
    public javax.swing.JCheckBox getUppercaseAttrOption() {
        return uppercaseAttrOption;
    }
    
    /**
     *
     * @param uppercaseAttrOption
     */
    public void setUppercaseAttrOption(javax.swing.JCheckBox uppercaseAttrOption) {
        this.uppercaseAttrOption = uppercaseAttrOption;
    }
    
    /**
     *
     * @return
     */
    public javax.swing.JCheckBox getUppercaseTagsOption() {
        return uppercaseTagsOption;
    }
    
    /**
     *
     * @param uppercaseTagsOption
     */
    public void setUppercaseTagsOption(javax.swing.JCheckBox uppercaseTagsOption) {
        this.uppercaseTagsOption = uppercaseTagsOption;
    }
    
    /**
     *
     * @return
     */
    public javax.swing.JCheckBox getWrapAttrOption() {
        return wrapAttrOption;
    }
    
    /**
     *
     * @param wrapAttrOption
     */
    public void setWrapAttrOption(javax.swing.JCheckBox wrapAttrOption) {
        this.wrapAttrOption = wrapAttrOption;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        dropEmptyParasOption = new javax.swing.JCheckBox();
        logicalEmphasisOption = new javax.swing.JCheckBox();
        uppercaseAttrOption = new javax.swing.JCheckBox();
        uppercaseTagsOption = new javax.swing.JCheckBox();
        indentOption = new javax.swing.JCheckBox();
        wrapAttrOption = new javax.swing.JCheckBox();

        dropEmptyParasOption.setSelected(true);
        dropEmptyParasOption.setText("Drop empty paras");
        dropEmptyParasOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        dropEmptyParasOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Bindings.bind(dropEmptyParasOption, adapter.getValueModel("dropEmptyParasOption"));

        logicalEmphasisOption.setSelected(true);
        logicalEmphasisOption.setText("Logical emphasis");
        logicalEmphasisOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        logicalEmphasisOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Bindings.bind(logicalEmphasisOption, adapter.getValueModel("logicalEmphasisOption"));

        uppercaseAttrOption.setText("Uppercase attributes");
        uppercaseAttrOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        uppercaseAttrOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Bindings.bind(uppercaseAttrOption, adapter.getValueModel("uppercaseAttrOption"));

        uppercaseTagsOption.setText("Uppercase tags");
        uppercaseTagsOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        uppercaseTagsOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Bindings.bind(uppercaseTagsOption, adapter.getValueModel("uppercaseTagsOption"));

        indentOption.setSelected(true);
        indentOption.setText("Indent");
        indentOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        indentOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Bindings.bind(indentOption, adapter.getValueModel("indentOption"));

        wrapAttrOption.setText("Wrap attributes");
        wrapAttrOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        wrapAttrOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Bindings.bind(wrapAttrOption, adapter.getValueModel("wrapAttrOption"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dropEmptyParasOption)
                    .add(logicalEmphasisOption)
                    .add(uppercaseAttrOption))
                .add(83, 83, 83)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(indentOption)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(uppercaseTagsOption)
                        .add(wrapAttrOption)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dropEmptyParasOption)
                    .add(indentOption))
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(logicalEmphasisOption)
                    .add(uppercaseTagsOption))
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(wrapAttrOption)
                    .add(uppercaseAttrOption))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox dropEmptyParasOption;
    private javax.swing.JCheckBox indentOption;
    private javax.swing.JCheckBox logicalEmphasisOption;
    private javax.swing.JCheckBox uppercaseAttrOption;
    private javax.swing.JCheckBox uppercaseTagsOption;
    private javax.swing.JCheckBox wrapAttrOption;
    // End of variables declaration//GEN-END:variables
    private JTidyOptionModel model;
}
