/*
 * AboutDialogView.java
 *
 * Created on August 4, 2007, 10:29 AM
 */

package net.sf.xpontus.modules.gui.components;

import java.awt.Frame;
import javax.swing.text.html.HTMLEditorKit;
import net.sf.xpontus.constants.XPontusConfigurationConstantsIF;
import net.sf.xpontus.utils.XPontusComponentsUtils;
import org.apache.commons.lang.text.StrBuilder;

/**
 *
 * @author  Owner
 */
public class AboutDialogView extends javax.swing.JDialog {

    /**
     * Creates new form AboutDialogView
     * @param parent
     * @param modal
     */
    public AboutDialogView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();


        StrBuilder sb = new StrBuilder(); 

        sb.append("<html><head></head><body>");

        sb.append("<p style=\"margin-top: 0\"><strong>Product version</strong> : ");
        sb.append("XPontus XML Editor 1.0.0-pre1");
        sb.append("</p>");

        sb.append("<p style=\"margin-top: 0\"><strong>Java</strong> : ");
        sb.append(System.getProperty("java.version") + " " + System.getProperty("java.vendor"));
        sb.append("</p>");


        sb.append("<p style=\"margin-top: 0\"><strong>System</strong> : ");
        sb.append(System.getProperty("os.name") + " " + System.getProperty("os.version"));
        sb.append("</p>");


        sb.append("<p style=\"margin-top: 0\"><strong>Userdir</strong> : ");
        sb.append(XPontusConfigurationConstantsIF.XPONTUS_HOME_DIR.getAbsolutePath());
        sb.append("</p>");


        sb.append("</body></html>");

        textPane.setEditorKit(new HTMLEditorKit());
        textPane.setContentType("text/html");
        textPane.setText(sb.toString());
    }

    /**
     * Default constructor
     */
    public AboutDialogView() {

        this((Frame) XPontusComponentsUtils.getTopComponent().getDisplayComponent(), true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        sysinfoScrollPane = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();
        bottomPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        licenseScrollPane = new javax.swing.JScrollPane();
        sysinfoTA = new javax.swing.JTextArea();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About XPontus XML Editor");

        textPane.setContentType("text/html");
        textPane.setEditable(false);
        sysinfoScrollPane.setViewportView(textPane);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton_onClick(evt);
            }
        });
        bottomPanel.add(closeButton);

        licenseScrollPane.setBorder(null);

        sysinfoTA.setBackground(getBackground());
        sysinfoTA.setColumns(20);
        sysinfoTA.setEditable(false);
        sysinfoTA.setFont(new java.awt.Font("Dialog", 0, 13));
        sysinfoTA.setLineWrap(true);
        sysinfoTA.setText("XPontus XML Editor is written by Yves Zoundi and distributed under the GPL License version 2.0. The software homepage is http://xpontus.sf.net/index.html ");
        sysinfoTA.setWrapStyleWord(true);
        licenseScrollPane.setViewportView(sysinfoTA);

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/xpontus/icons/Xpontus2.PNG"))); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, logoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, licenseScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .add(bottomPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, sysinfoScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(logoLabel)
                .add(18, 18, 18)
                .add(licenseScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(sysinfoScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(bottomPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButton_onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton_onClick
        setVisible(false);    
}//GEN-LAST:event_closeButton_onClick
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane licenseScrollPane;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JScrollPane sysinfoScrollPane;
    private javax.swing.JTextArea sysinfoTA;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables
}
