/*
 * GotoLineView.java
 *
 * Created on August 26, 2007, 4:57 PM
 * 
 * 
 * Copyright (C) 2005-2008 Yves Zoundi
 * 
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * 
 */
package net.sf.xpontus.modules.gui.components;

import java.awt.Frame;
import java.awt.event.ActionListener;
import java.beans.EventHandler;
import net.sf.xpontus.controllers.impl.GotoLineController;
import net.sf.xpontus.utils.XPontusComponentsUtils;

/**
 * Goto line dialog
 * @author Yves Zoundi <yveszoundi at users dot sf dot net>
 * @version 0.0.1
 */
public class GotoLineView extends javax.swing.JDialog {

    /** Creates new form GotoLineView
     * @param parent
     * @param modal 
     */
    public GotoLineView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        controller = new GotoLineController(this);
        initComponents();
        
        this.lineNumberTF.setValue(new Integer(1));
        this.columnNumberTF.setValue(new Integer(1));
    }

    public int getLine(){
        return Integer.parseInt(this.lineNumberTF.getValue().toString());
    }
    
    public int getColumn(){
        return Integer.parseInt(this.columnNumberTF.getValue().toString());
    }
    
    public GotoLineView() {
        this((Frame) XPontusComponentsUtils.getTopComponent().getDisplayComponent(), false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findButton = new javax.swing.JButton();
        lineNumberTF = new javax.swing.JFormattedTextField();
        bottomPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        columnLabel = new javax.swing.JLabel();
        columnNumberTF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Go to line");

        findButton.setText("Find line");
        findButton.addActionListener(
            (ActionListener)EventHandler.create(
                ActionListener.class,
                controller,
                GotoLineController.GOTO_LINE_METHOD)
        );

        lineNumberTF.setToolTipText("The line number");

        closeButton.setText("Close");
        closeButton.addActionListener(
            (ActionListener)EventHandler.create(
                ActionListener.class,
                controller,
                GotoLineController.CLOSE_WINDOW_METHOD)
        );
        bottomPanel.add(closeButton);

        columnLabel.setText("  Column");

        columnNumberTF.setToolTipText("The column is mandatory, if not found it will be reset to 1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, bottomPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(findButton)
                            .add(columnLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lineNumberTF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .add(columnNumberTF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                .add(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(findButton)
                    .add(lineNumberTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(columnLabel)
                    .add(columnNumberTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(bottomPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel columnLabel;
    private javax.swing.JFormattedTextField columnNumberTF;
    private javax.swing.JButton findButton;
    private javax.swing.JFormattedTextField lineNumberTF;
    // End of variables declaration//GEN-END:variables
    private GotoLineController controller;
}
