/*
 * JStatusBar.java
 *
 * Created on February 14, 2006, 2:41 AM
 *
 * Copyright (C) 2005-2007 Yves Zoundi
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
package net.sf.xpontus.modules.gui.components;

import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.awt.Insets;
import java.io.File;
import javax.swing.JComponent;

/**
 *
 * @author Yves Zoundi
 */
public class JStatusBar extends javax.swing.JPanel {

    /** Creates new form JStatusBar */
    public JStatusBar() {
        initComponents();
        addComponents();
    }

    private void addComponents() {
        jLabel1 = new javax.swing.JLabel();
        lineLabel = new javax.swing.JLabel();
        operationPanel = new javax.swing.JPanel(new GridLayout());

        GridBagConstraints gbc = new GridBagConstraints(0, 0, 1, 1, 0.5, 1,
                GridBagConstraints.NORTHWEST, GridBagConstraints.NONE,
                new Insets(2, 2, 2, 2), 0, 0);

        add(lineLabel, gbc);

        gbc = new GridBagConstraints(1, 0, 1, 1, 0.5, 1,
                GridBagConstraints.NORTHWEST, GridBagConstraints.NONE,
                new Insets(2, 2, 2, 2), 0, 0);

        add(jLabel1, gbc);

        gbc = new GridBagConstraints(2, 0, 1, 2, 0.5, 1,
                GridBagConstraints.NORTHWEST,
                GridBagConstraints.HORIZONTAL, new Insets(2, 2, 2, 2), 0, 0);

        add(operationPanel, gbc);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2)));
        setMinimumSize(new java.awt.Dimension(400, 25));
        setPreferredSize(new java.awt.Dimension(400, 25));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    public void addOperationComponent(JComponent c) {
        operationPanel.add(c);
        operationPanel.invalidate();
        operationPanel.revalidate();
        operationPanel.repaint();
    }

    public void removeOperationComponent(JComponent c) {
        operationPanel.remove(c);
        operationPanel.invalidate();
        operationPanel.revalidate();
        operationPanel.repaint();
    }

    /**
     *
     * @param message
     */
    public void setMessage(String message) {
        this.jLabel1.setText(message);
    }

    public void updateLineInfo(String lineInfo) {
        lineLabel.setText(lineInfo);
    }

    public void setMessageWithTip(String message) {
        int taille = message.length();
        int pos = message.lastIndexOf(File.separator);
        String tip = message.substring(pos + 1, taille);
        jLabel1.setToolTipText(message);
        this.jLabel1.setText(tip);
    }

    public void setLineMessage(String lineInfo) {
        lineLabel.setText(lineInfo);
    }

    /**
     *
     * @return
     */
    public String getMessage() {
        return this.jLabel1.getText();
    }
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lineLabel;
    private javax.swing.JPanel operationPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
