/*
 * PreferencesView.java
 *
 * Created on 27 janvier 2008, 17:45
 */
package net.sf.xpontus.modules.gui.components;

import java.awt.Frame;
import net.sf.xpontus.modules.gui.components.preferences.GeneralPanel;
import net.sf.xpontus.utils.XPontusComponentsUtils;

/**
 *
 * @author  Yves Zoundi <yveszoundi at users dot sf dot net>
 */
public class PreferencesView extends javax.swing.JDialog {

    /** Creates new form PreferencesView
     * @param parent
     * @param modal 
     */
    public PreferencesView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public PreferencesView() { 
         this((Frame) XPontusComponentsUtils.getTopComponent().getDisplayComponent(), true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panePanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new GeneralPanel();
        advancedPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        buttonsPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setTitle("Preferences");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        mainPanel.setLayout(new java.awt.BorderLayout());

        panePanel.setLayout(new java.awt.BorderLayout());

        tabbedPane.addTab("General", jPanel1);

        panePanel.add(tabbedPane, java.awt.BorderLayout.CENTER);

        mainPanel.add(panePanel, java.awt.BorderLayout.CENTER);

        advancedPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setText("Advanced...");
        advancedPanel.add(jButton1);

        mainPanel.add(advancedPanel, java.awt.BorderLayout.SOUTH);

        add(mainPanel, java.awt.BorderLayout.CENTER);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(closeButton);

        add(buttonsPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false); 
    }//GEN-LAST:event_closeDialog

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
}//GEN-LAST:event_closeButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel advancedPanel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panePanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
