/*
 * ScenarioManagerView.java
 *
 * Created on August 22, 2007, 6:02 PM
 * 
 * 
 * Copyright (C) 2005-2008 Yves Zoundi
 * 
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * 
 */
package net.sf.xpontus.modules.gui.components;

import java.awt.Frame;
import java.awt.event.ActionListener;
import java.beans.EventHandler;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JList;
import net.sf.xpontus.controllers.impl.ScenarioManagerController;
import net.sf.xpontus.utils.XPontusComponentsUtils;

/**
 * Dialog to manage user transformations
 * @version 0.0.1
 * @author  Yves Zoundi
 */
public class ScenarioManagerView extends javax.swing.JDialog {

    /** Creates new form ScenarioManagerView 
     * @param parent 
     * @param modal 
     */
    public ScenarioManagerView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        controller = new ScenarioManagerController(this);
        initComponents();
        
    }

    /**
     * Default constructor
     */
    public ScenarioManagerView() {
        this((Frame) XPontusComponentsUtils.getTopComponent().getDisplayComponent(), true);
    }

    /**
     * 
     * @return
     */
    public JList getScenariosList() {
        return scenariosList;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        scenariosList = new javax.swing.JList();
        newButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage scenarios");

        scenariosList.setModel(new DefaultComboBoxModel());
        scrollPane.setViewportView(scenariosList);

        newButton.setText("New");
        newButton.addActionListener(
            (ActionListener)EventHandler.create(
                ActionListener.class,
                controller,
                ScenarioManagerController.NEW_SCENARIO_METHOD)
        );

        editButton.setText("Edit");
        editButton.addActionListener(
            (ActionListener)EventHandler.create(
                ActionListener.class,
                controller,
                ScenarioManagerController.EDIT_SCENARIO_METHOD)
        );

        deleteButton.setText("Delete");
        deleteButton.addActionListener(
            (ActionListener)EventHandler.create(
                ActionListener.class,
                controller,
                ScenarioManagerController.REMOVE_SCENARIO_METHOD)
        );

        closeButton.setText("Close window");
        closeButton.addActionListener(
            (ActionListener)EventHandler.create(
                ActionListener.class,
                controller,
                ScenarioManagerController.CLOSE_WINDOW_METHOD)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(37, 37, 37)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(closeButton)
                    .add(scrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(48, 48, 48)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(newButton)
                    .add(editButton)
                    .add(deleteButton))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {deleteButton, editButton, newButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(newButton)
                        .add(18, 18, 18)
                        .add(editButton)
                        .add(29, 29, 29)
                        .add(deleteButton))
                    .add(scrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 55, Short.MAX_VALUE)
                .add(closeButton)
                .add(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton newButton;
    private javax.swing.JList scenariosList;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    private ScenarioManagerController controller;
}
