/*
 * SchemaValidationView.java
 *
 * Created on December 17, 2007, 2:53 PM
 */

package net.sf.xpontus.plugins.validation.schemavalidation;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.adapter.ComboBoxAdapter;
import com.jgoodies.binding.beans.BeanAdapter;
import com.jgoodies.binding.value.ValueHolder;
import com.jgoodies.binding.value.ValueModel;
import java.awt.Frame;
import java.awt.event.ActionListener;
import java.beans.EventHandler;
import java.util.ArrayList;
import net.sf.xpontus.utils.XPontusComponentsUtils;

/**
 *
 * @author  Yves Zoundi <yveszoundi at users dot sf dot net>
 */
public class SchemaValidationView extends javax.swing.JDialog {
    
    /** Creates new form SchemaValidationView
     * @param parent
     * @param modal 
     */
    public SchemaValidationView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        model = new SchemaValidationModel();
        adapter = new BeanAdapter(model, true);
        ArrayList strings = new ArrayList();
        strings.add("XML Schema");
        strings.add("DTD");
        strings.add("Relax NG"); 
         ValueModel selectionHolder = new ValueHolder("Selecta schema type");
        typeAdapter = new ComboBoxAdapter(strings, selectionHolder);
        controller = new SchemaValidationController(this);
        initComponents();
    }
    
    public SchemaValidationView(){
        this( (Frame)XPontusComponentsUtils.getTopComponent().getDisplayComponent(), true);
    }

    /**
     * 
     * @return
     */
    public SchemaValidationModel getModel() {
        return model;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanel = new javax.swing.JPanel();
        inputButton = new javax.swing.JButton();
        inputTF = new javax.swing.JTextField();
        useCurrentDocumentOption = new javax.swing.JRadioButton();
        useExternalDocumentOption = new javax.swing.JRadioButton();
        Bindings.bind(useExternalDocumentOption, adapter.getValueModel("useCurrentDocument"), Boolean.FALSE);
        schemaPanel = new javax.swing.JPanel();
        schemaButton = new javax.swing.JButton();
        schemaTF = new javax.swing.JTextField();
        schemaLabel = new javax.swing.JLabel();
        schemaTypeList = new javax.swing.JComboBox();
        bottomPanel = new javax.swing.JPanel();
        validateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Schema validation");

        inputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Input options"));

        inputButton.setText("Input");
        inputButton.addActionListener(
            (ActionListener)EventHandler.create(
                ActionListener.class,
                controller,
                SchemaValidationController.INPUT_METHOD)
        );

        Bindings.bind(inputTF, adapter.getValueModel("input"));

        useCurrentDocumentOption.setText("Use current document");
        Bindings.bind(useCurrentDocumentOption, adapter.getValueModel("useCurrentDocument"), Boolean.TRUE);
        useCurrentDocumentOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useCurrentDocumentOptionActionPerformed(evt);
            }
        });

        useExternalDocumentOption.setText("Use external document");
        useExternalDocumentOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useExternalDocumentOptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(inputButton)
                        .addGap(51, 51, 51)
                        .addComponent(inputTF, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(useCurrentDocumentOption)
                        .addGap(33, 33, 33)
                        .addComponent(useExternalDocumentOption)))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputButton)
                    .addComponent(inputTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useCurrentDocumentOption)
                    .addComponent(useExternalDocumentOption))
                .addContainerGap())
        );

        schemaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Schema options"));

        schemaButton.setText("Schema file");
        schemaButton.addActionListener(
            (ActionListener)EventHandler.create(
                ActionListener.class,
                controller,
                SchemaValidationController.SCHEMA_METHOD)
        );

        Bindings.bind(schemaTF, adapter.getValueModel("schema"));

        schemaLabel.setText("Schema type");

        schemaTypeList.setModel(typeAdapter);

        javax.swing.GroupLayout schemaPanelLayout = new javax.swing.GroupLayout(schemaPanel);
        schemaPanel.setLayout(schemaPanelLayout);
        schemaPanelLayout.setHorizontalGroup(
            schemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schemaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(schemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schemaButton)
                    .addComponent(schemaLabel))
                .addGap(51, 51, 51)
                .addGroup(schemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schemaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(schemaTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        schemaPanelLayout.setVerticalGroup(
            schemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schemaPanelLayout.createSequentialGroup()
                .addGroup(schemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schemaButton)
                    .addComponent(schemaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(schemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schemaLabel)
                    .addComponent(schemaTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        validateButton.setText("Validate");
        validateButton.addActionListener(
            (ActionListener)EventHandler.create(
                ActionListener.class,
                controller,
                SchemaValidationController.HANDLE_METHOD)
        );
        bottomPanel.add(validateButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(
            (ActionListener)EventHandler.create(
                ActionListener.class,
                controller,
                SchemaValidationController.CLOSE_METHOD)
        );
        bottomPanel.add(cancelButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bottomPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(schemaPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(schemaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void useCurrentDocumentOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useCurrentDocumentOptionActionPerformed
        inputButton.setEnabled(false);
        model.setInput("");
    }//GEN-LAST:event_useCurrentDocumentOptionActionPerformed

    private void useExternalDocumentOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useExternalDocumentOptionActionPerformed
        inputButton.setEnabled(true);
    }//GEN-LAST:event_useExternalDocumentOptionActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton inputButton;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JTextField inputTF;
    private javax.swing.JButton schemaButton;
    private javax.swing.JLabel schemaLabel;
    private javax.swing.JPanel schemaPanel;
    private javax.swing.JTextField schemaTF;
    private javax.swing.JComboBox schemaTypeList;
    private javax.swing.JRadioButton useCurrentDocumentOption;
    private javax.swing.JRadioButton useExternalDocumentOption;
    private javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables
    private SchemaValidationModel model;
    private BeanAdapter adapter;
    private ComboBoxAdapter typeAdapter;
    private SchemaValidationController controller;
}
